// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ChallengeContext))]
    [Migration("20250109135858_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entitie.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuit = 20304050601L,
                            Dni = 20304050,
                            Email = "maradona10@argentina.com",
                            LastName = "Maradona",
                            Nacimiento = new DateTime(1960, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Diego",
                            Phone = 1140000001
                        },
                        new
                        {
                            Id = 2,
                            Cuit = 20708090101L,
                            Dni = 40708090,
                            Email = "messi10@argentina.com",
                            LastName = "Messi",
                            Nacimiento = new DateTime(1987, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lionel",
                            Phone = 1140000002
                        },
                        new
                        {
                            Id = 3,
                            Cuit = 20333333401L,
                            Dni = 30333333,
                            Email = "sabatini@argentina.com",
                            LastName = "Sabatini",
                            Nacimiento = new DateTime(1970, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gabriela",
                            Phone = 1140000003
                        },
                        new
                        {
                            Id = 4,
                            Cuit = 20123456701L,
                            Dni = 10123456,
                            Email = "papa_francisco@vaticano.com",
                            LastName = "Bergoglio",
                            Nacimiento = new DateTime(1936, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jorge",
                            Phone = 1140000004
                        },
                        new
                        {
                            Id = 5,
                            Cuit = 20567890101L,
                            Dni = 50678901,
                            Email = "ginobili20@argentina.com",
                            LastName = "Ginóbili",
                            Nacimiento = new DateTime(1977, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Manuel",
                            Phone = 1140000005
                        },
                        new
                        {
                            Id = 6,
                            Cuit = 20122334455L,
                            Dni = 20122334,
                            Email = "pergolini@cqc.com",
                            LastName = "Pergolini",
                            Nacimiento = new DateTime(1964, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mario",
                            Phone = 1140000006
                        },
                        new
                        {
                            Id = 7,
                            Cuit = 20111223344L,
                            Dni = 20111223,
                            Email = "francella@actor.com",
                            LastName = "Francella",
                            Nacimiento = new DateTime(1955, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Guillermo",
                            Phone = 1140000007
                        },
                        new
                        {
                            Id = 8,
                            Cuit = 20444444401L,
                            Dni = 40444444,
                            Email = "darin@actor.com",
                            LastName = "Darín",
                            Nacimiento = new DateTime(1957, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ricardo",
                            Phone = 1140000010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
